language: generic

os: osx
osx_image: xcode8.3

env:
  - TARGET_PLUGIN=GMIC

before_install:
  - brew update >& /dev/null && brew install ccache
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - bash ./travis/build-osx.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
